name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: ./Multitenancy
        run: terraform init

      - name: Terraform Workspace Development
        working-directory: ./Multitenancy
        run: |
          terraform workspace new development || terraform workspace select development
          terraform apply -auto-approve

      - name: Terraform Workspace Staging
        working-directory: ./Multitenancy
        run: |
          terraform workspace new staging || terraform workspace select staging
          terraform apply -auto-approve

      - name: Terraform Workspace Production
        working-directory: ./Multitenancy
        run: |
          terraform workspace new production || terraform workspace select production
          terraform apply -auto-approve
